apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gop-fileserver
  name: gop-fileserver
  namespace: default
spec:
  containers:
  - image: kodekloud/fileserver
    name: gop-fileserver
    volumeMounts:
      - mountPath: "/web"
        name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc