apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      volumes:
        - name: drupal-myssql-pv-storage
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            subPath: dbdata
            name: drupal-myssql-pv-storage
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret 
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret 
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret 
                key: MYSQL_USER